processed 10 tasks

task 2 'run'. lines 5-13:
{
  "gas_used": 151705,
  "status": {
    "Keep": "Executed"
  }
}

task 3 'view'. lines 15-15:
store key 0xf2aa2eae4ceaae88b308fc904975e4ae::PluginMarketplace::PluginRegistry {
    next_plugin_id: 1
    plugins: [
    ]
}

task 5 'run'. lines 19-27:
Error: error[E04007]: incompatible types
   ┌─ /tmp/.tmpBuetqi:23:9
   │
22 │     fun main(sender: signer) {
   │                      ------ Given: 'signer'
23 │         PluginMarketplace::register_plugin(sender, b"member_manager_plugin", b"ipfs:://xxxxxx");
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid call of 'FreePlugin::PluginMarketplace::register_plugin'. Invalid argument for parameter 'a0'
   │
   ┌─ /tmp/.tmp2NaCvw:57:43
   │
57 │     native public fun register_plugin(a0: &signer, a1: vector<u8>, a2: vector<u8>): u64;
   │                                           ------- Expected: '&signer'



task 6 'view'. lines 29-29:
store key 0xf2aa2eae4ceaae88b308fc904975e4ae::PluginMarketplace::PluginRegistry {
    next_plugin_id: 1
    plugins: [
    ]
}

task 7 'run'. lines 31-53:
Error: error[E04007]: incompatible types
   ┌─ /tmp/.tmpO6rENj:38:9
   │  
35 │       fun main(sender: signer) {
   │                        ------ Given: 'signer'
   ·  
38 │ ╭         PluginMarketplace::publish_plugin_version(
39 │ │             sender, 
40 │ │             1,
41 │ │             b"v0.1.0", 
   · │
47 │ │             b"ipfs:://xxxxxx"
48 │ │         );
   │ ╰─────────^ Invalid call of 'FreePlugin::PluginMarketplace::publish_plugin_version'. Invalid argument for parameter 'a0'
   │  
   ┌─ /tmp/.tmp2NaCvw:56:50
   │
56 │     native public fun publish_plugin_version(a0: &signer, a1: u64, a2: vector<u8>, a3: vector<vector<u8>>, a4: vector<vector<u8>>, a5: vector<vector<u8>>, a6: vector<vector<u8>>, a7: vector<u8>, a8: vector<u8>);
   │                                                  ------- Expected: '&signer'



task 8 'view'. lines 55-55:
store key 0xf2aa2eae4ceaae88b308fc904975e4ae::PluginMarketplace::PluginRegistry {
    next_plugin_id: 1
    plugins: [
    ]
}

task 9 'run'. lines 57-79:
Error: error[E04007]: incompatible types
   ┌─ /tmp/.tmpqKiSxx:64:9
   │  
61 │       fun main(sender: signer) {
   │                        ------ Given: 'signer'
   ·  
64 │ ╭         PluginMarketplace::publish_plugin_version(
65 │ │             sender, 
66 │ │             2,
67 │ │             b"v0.1.0", 
   · │
73 │ │             b"ipfs:://xxxxxx"
74 │ │         );
   │ ╰─────────^ Invalid call of 'FreePlugin::PluginMarketplace::publish_plugin_version'. Invalid argument for parameter 'a0'
   │  
   ┌─ /tmp/.tmp2NaCvw:56:50
   │
56 │     native public fun publish_plugin_version(a0: &signer, a1: u64, a2: vector<u8>, a3: vector<vector<u8>>, a4: vector<vector<u8>>, a5: vector<vector<u8>>, a6: vector<vector<u8>>, a7: vector<u8>, a8: vector<u8>);
   │                                                  ------- Expected: '&signer'


