processed 10 tasks

task 2 'run'. lines 5-13:
{
  "gas_used": 90066,
  "status": {
    "Keep": "Executed"
  }
}

task 3 'view'. lines 15-15:
key 0x9960cd7c0a0c353336780f69400f00cf::FreepaiDAO::FreepaiDAO {
    name: 4672656570616944414f
    installed_plugins: [
    ]
}

task 5 'run'. lines 19-32:
{
  "gas_used": 53558,
  "status": {
    "Keep": "Executed"
  }
}

task 6 'view'. lines 34-34:
key 0x9960cd7c0a0c353336780f69400f00cf::FreepaiDAO::FreepaiDAO {
    name: 4672656570616944414f
    installed_plugins: [
        store 0x9960cd7c0a0c353336780f69400f00cf::FreepaiDAO::InstalledPluginInfo {
            plugin_id: 1
            plugin_version: 1
            granted_caps: 0102
        },
    ]
}

task 8 'run'. lines 38-51:
{
  "gas_used": 57665,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'view'. lines 53-53:
key 0x9960cd7c0a0c353336780f69400f00cf::FreepaiDAO::FreepaiDAO {
    name: 4672656570616944414f
    installed_plugins: [
        store 0x9960cd7c0a0c353336780f69400f00cf::FreepaiDAO::InstalledPluginInfo {
            plugin_id: 1
            plugin_version: 1
            granted_caps: 0102
        },
        store 0x9960cd7c0a0c353336780f69400f00cf::FreepaiDAO::InstalledPluginInfo {
            plugin_id: 2
            plugin_version: 1
            granted_caps: 0304
        },
    ]
}
