processed 10 tasks

task 2 'run'. lines 5-13:
{
  "gas_used": 151705,
  "status": {
    "Keep": "Executed"
  }
}

task 3 'view'. lines 15-15:
store key 0xf2aa2eae4ceaae88b308fc904975e4ae::PluginMarketplace::PluginRegistry {
    next_plugin_id: 1
    plugins: [
    ]
}

task 5 'run'. lines 19-27:
Error: error[E04007]: incompatible types
   ┌─ /tmp/.tmp5iyD4Q:23:9
   │
22 │     fun main(sender: signer) {
   │                      ------ Given: 'signer'
23 │         PluginMarketplace::register_plugin(sender, b"member_manager_plugin", b"ipfs:://xxxxxx");
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid call of 'FreePlugin::PluginMarketplace::register_plugin'. Invalid argument for parameter 'a0'
   │
   ┌─ /tmp/.tmpOY2Eof:57:43
   │
57 │     native public fun register_plugin(a0: &signer, a1: vector<u8>, a2: vector<u8>): u64;
   │                                           ------- Expected: '&signer'



task 6 'view'. lines 29-29:
store key 0xf2aa2eae4ceaae88b308fc904975e4ae::PluginMarketplace::PluginRegistry {
    next_plugin_id: 1
    plugins: [
    ]
}

task 8 'run'. lines 33-41:
Error: error[E04007]: incompatible types
   ┌─ /tmp/.tmpVTSrIU:37:9
   │
36 │     fun main(sender: signer) {
   │                      ------ Given: 'signer'
37 │         PluginMarketplace::register_plugin(sender, b"stake_manager_plugin", b"ipfs:://xxxxxx");
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid call of 'FreePlugin::PluginMarketplace::register_plugin'. Invalid argument for parameter 'a0'
   │
   ┌─ /tmp/.tmpOY2Eof:57:43
   │
57 │     native public fun register_plugin(a0: &signer, a1: vector<u8>, a2: vector<u8>): u64;
   │                                           ------- Expected: '&signer'



task 9 'view'. lines 43-43:
store key 0xf2aa2eae4ceaae88b308fc904975e4ae::PluginMarketplace::PluginRegistry {
    next_plugin_id: 1
    plugins: [
    ]
}
