processed 7 tasks

task 2 'run'. lines 5-13:
{
  "gas_used": 154696,
  "status": {
    "Keep": "Executed"
  }
}

task 3 'view'. lines 15-15:
store key 0x7da9cd8048a4620fda9e22977750c517::ExtensionPoint::Registry {
    next_id: 1
    items: [
    ]
}

task 4 'run'. lines 17-24:
{
  "gas_used": 23872,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x7da9cd8048a4620fda9e22977750c517",
            "name": "ExtensionPoint"
          }
        },
        25606
      ]
    }
  }
}

task 6 'run'. lines 28-35:
{
  "gas_used": 17943,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x7da9cd8048a4620fda9e22977750c517",
            "name": "ExtensionPoint"
          }
        },
        25858
      ]
    }
  }
}
